"""Calibration reliability data for the operational dashboard.

For each (sport, bet_type, prob_bucket), reports:
  - n          (settled picks in this bucket)
  - mean_pred  (mean predicted prob)
  - mean_actual (realized win rate)
  - delta      (mean_pred - mean_actual; positive = overconfident model)
  - brier      (per-bucket Brier contribution)

Powers a "Calibration" tab that renders reliability diagrams (predicted
vs actual line per market) so calibration drift surfaces immediately
instead of hiding in CSVs run on demand.

The data is the same shape `engine/empirical_calibration.py` builds
internally for fitting; this module just exposes it for read-only
display. No new computation, no fitting — pure diagnostics.

Why this exists (#185 in player_aggregation_plan)
-------------------------------------------------
Under "be right, not edge-first" the single most important question
is "when the model says 60%, are 60% of those bets winning?" Today
that lives in CSV reports run by hand. Surfacing it in the UI means
calibration drift becomes obvious, not invisible.
"""

from __future__ import annotations

import logging
from typing import Iterable

logger = logging.getLogger(__name__)


# Default bucket edges — 10 bins covering [0, 1]. Overrideable per call
# if a sport wants finer/coarser resolution.
DEFAULT_N_BUCKETS = 10


def _settled_picks_for_sport(sport: str, days: int | None = 0,
                              respect_cutoff: bool = True) -> list[dict]:
    """Pull every settled (W/L) pick with a model_prob for the sport.

    `days=0` (default) means full history (subject to the model-stack
    cutoff); otherwise restrict to `date >= now - days`.

    `respect_cutoff=True` (default) defers to ``engine.model_cutoffs``
    so picks generated by the OLD (pre-MC+GBM) stack don't pollute
    the calibration data with bleed from a model that no longer exists.
    Set False for full-history reporting (e.g. backtest replay)."""
    sport = sport.lower()
    cutoff_date: str | None = None
    if respect_cutoff:
        try:
            from .model_cutoffs import get_cutoff
            cutoff_date = get_cutoff(sport)
        except Exception:
            cutoff_date = None
    try:
        if sport == "mlb":
            from .db import get_conn
            table = "picks"
        elif sport == "nhl":
            from .nhl_tracker._helpers import _get_nhl_db
            conn = _get_nhl_db()
            table = "nhl_picks"
            return _pull(conn, table, days, cutoff_date)
        elif sport == "nba":
            from .nba_db import get_conn
            table = "nba_picks"
        elif sport == "tennis":
            from .tennis_db import get_conn
            table = "tennis_picks"
        else:
            return []
        conn = get_conn()
        return _pull(conn, table, days, cutoff_date)
    except Exception as exc:
        logger.warning("calibration_diagnostics fetch %s failed: %s", sport, exc)
        return []


def _pull(conn, table: str, days: int | None,
           cutoff_date: str | None = None) -> list[dict]:
    where_clause = ("WHERE result IN ('W','L') AND model_prob IS NOT NULL")
    args: list = []
    # Day-window filter (relative)
    if days and days > 0:
        from datetime import datetime, timedelta
        rel_cutoff = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")
        where_clause += " AND date >= ?"
        args.append(rel_cutoff)
    # Model-stack cutoff (absolute, per engine.model_cutoffs)
    if cutoff_date:
        where_clause += " AND date >= ?"
        args.append(cutoff_date)
    rows = conn.execute(
        f"SELECT bet_type, model_prob, result FROM {table} {where_clause}",
        args,
    ).fetchall()
    out = []
    for r in rows:
        try:
            out.append({
                "bet_type":   r["bet_type"],
                "model_prob": float(r["model_prob"]),
                "outcome":    1.0 if r["result"] == "W" else 0.0,
            })
        except (TypeError, ValueError):
            continue
    return out


def reliability_buckets(samples: list[tuple[float, float]],
                         n_buckets: int = DEFAULT_N_BUCKETS) -> list[dict]:
    """Bin (predicted, actual) pairs into n_buckets and compute the
    reliability diagram data per bucket. Empty buckets carry n=0."""
    from collections import defaultdict
    buckets: dict[int, list[tuple[float, float]]] = defaultdict(list)
    for p, y in samples:
        idx = min(n_buckets - 1, max(0, int(p * n_buckets)))
        buckets[idx].append((p, y))
    out = []
    for idx in range(n_buckets):
        rows = buckets.get(idx) or []
        if not rows:
            out.append({
                "bucket":      idx,
                "lo":          round(idx / n_buckets, 2),
                "hi":          round((idx + 1) / n_buckets, 2),
                "n":           0,
                "mean_pred":   None,
                "mean_actual": None,
                "delta":       None,
                "brier":       None,
            })
            continue
        n = len(rows)
        mp = sum(p for p, _ in rows) / n
        ma = sum(y for _, y in rows) / n
        brier = sum((p - y) ** 2 for p, y in rows) / n
        out.append({
            "bucket":      idx,
            "lo":          round(idx / n_buckets, 2),
            "hi":          round((idx + 1) / n_buckets, 2),
            "n":           n,
            "mean_pred":   round(mp, 4),
            "mean_actual": round(ma, 4),
            "delta":       round(mp - ma, 4),
            "brier":       round(brier, 4),
        })
    return out


def reliability_for_sport(sport: str, *,
                           days: int | None = 0,
                           n_buckets: int = DEFAULT_N_BUCKETS,
                           by_bet_type: bool = True) -> dict:
    """Returns per-(sport, bet_type) reliability buckets + an
    `overall` key aggregating across bet types.

    {
      "sport": "mlb",
      "days": 0,
      "overall": [bucket, bucket, ...],
      "by_bet_type": {
        "ML":   [bucket, ...],
        "RL":   [bucket, ...],
        ...
      }
    }
    """
    picks = _settled_picks_for_sport(sport, days=days)
    overall_samples = [(p["model_prob"], p["outcome"]) for p in picks]
    out: dict = {
        "sport":   sport,
        "days":    days,
        "n_total": len(picks),
        "overall": reliability_buckets(overall_samples, n_buckets),
    }
    if by_bet_type:
        from collections import defaultdict
        groups: dict[str, list[tuple[float, float]]] = defaultdict(list)
        for p in picks:
            groups[p["bet_type"]].append((p["model_prob"], p["outcome"]))
        out["by_bet_type"] = {
            bt: reliability_buckets(samples, n_buckets)
            for bt, samples in groups.items()
        }
    # Headline metrics
    if overall_samples:
        n = len(overall_samples)
        brier = sum((p - y) ** 2 for p, y in overall_samples) / n
        # Expected calibration error (ECE) = weighted mean |delta| across buckets.
        ece_num = 0.0
        ece_den = 0
        for b in out["overall"]:
            if b["n"] and b["delta"] is not None:
                ece_num += b["n"] * abs(b["delta"])
                ece_den += b["n"]
        out["headline"] = {
            "brier": round(brier, 4),
            "ece":   round(ece_num / ece_den, 4) if ece_den else None,
        }
    else:
        out["headline"] = {"brier": None, "ece": None}
    return out


def reliability_all_sports(days: int | None = 0,
                            n_buckets: int = DEFAULT_N_BUCKETS) -> dict:
    """Bulk version — one call returns all four sports."""
    return {
        sport: reliability_for_sport(sport, days=days, n_buckets=n_buckets)
        for sport in ("mlb", "nhl", "nba", "tennis")
    }


__all__ = [
    "reliability_buckets",
    "reliability_for_sport",
    "reliability_all_sports",
]
