"""
Per-sport model-stack cutoff dates — shared across diagnostics.

Each sport has a date when the current MC + GBM ensemble landed in
production. Settled picks BEFORE this date were generated by a
different (typically worse) model that no longer exists. Including
them in calibration / autopsy / floor-derivation contaminates the
metrics with bleed from a model the engine is no longer running.

Diagnostics that should respect the cutoff:
- ``engine.edge_floors``    — per-cell floor derivation
- ``engine.tracker_autopsy``— "current model" performance view
- ``engine.clv_diagnostics``— current-model CLV signal

If a tool wants the full history (e.g. a long-term replay), it can
pass ``since=None`` or its own date — these constants are the
default, not a hard filter.

Update the dict here when a model stack ships; downstream consumers
pick it up automatically.
"""

from __future__ import annotations

# YYYY-MM-DD; None means no cutoff is known and the consumer should
# fall back to the full table.
MODEL_CUTOFFS: dict[str, str | None] = {
    "mlb": "2026-04-01",  # MC + GBM stable since early April
    "nhl": "2026-04-19",  # MC + GBM landed at NHL playoff start
    "nba": "2026-04-15",  # MC + GBM stable from playoff start
    "tennis": "2026-05-13",  # walk-forward shrinkage shipped 2026-05-13
}


def get_cutoff(sport: str) -> str | None:
    """Return the cutoff date for ``sport`` or None if unknown."""
    return MODEL_CUTOFFS.get((sport or "").lower())


__all__ = ["MODEL_CUTOFFS", "get_cutoff"]
