"""
Record a live pick into the per-sport live_picks_<sport> table.

The pick payload is exactly the dict shape that `engine.live._picks
.generate_live_picks` produces — sport, game_id, matchup, bet_type,
pick text, odds, model_prob, implied_prob, edge_pct, and a `snapshot`
sub-dict carrying the period/clock/score/remaining-seconds at lock
time. The recorder maps `bet_type` to a `market_scope` (which the
settler uses to know when the pick is resolvable) and persists a
single row.

The market_scope inference rules:

  Full game (NBA): bet_type == 'ML' / 'SPREAD' / 'TOTAL' /
                   'ALT SPREAD' / 'ALT TOTAL' → 'full'
  NBA quarter:     bet_type startswith 'Q1 ' .. 'Q4 ' → 'Q1'..'Q4'
  NBA half:        bet_type startswith '1H ' / '2H ' → 'H1'/'H2'
  NHL period:      bet_type startswith 'P1 ' / 'P2 ' / 'P3 ' → 'P1'..'P3'

Anything we don't recognise falls back to 'full' so the row still
settles when the game ends — better than silently dropping the lock.
"""

from __future__ import annotations
import logging
from datetime import datetime, timezone

from ._schema import ensure_table, get_conn, table_name
from .._tz import et_today_str

logger = logging.getLogger(__name__)


def _market_scope_from_bet_type(bet_type: str) -> str:
    """Map an `engine.live._picks` bet_type string to the canonical
    market_scope used by the settler. See module docstring for rules.
    """
    if not isinstance(bet_type, str) or not bet_type:
        return "full"
    bt = bet_type.strip()
    bt_upper = bt.upper()

    # NBA quarter
    for q in ("Q1", "Q2", "Q3", "Q4"):
        if bt_upper.startswith(q + " "):
            return q
    # NBA half — bet_type uses "1H " / "2H " prefix
    if bt_upper.startswith("1H "):
        return "H1"
    if bt_upper.startswith("2H "):
        return "H2"
    # NHL period — bet_type uses "P1 " / "P2 " / "P3 " prefix
    for p in ("P1", "P2", "P3"):
        if bt_upper.startswith(p + " "):
            return p
    return "full"


def record_live_pick(sport: str, pick: dict) -> int:
    """Insert one live pick row. Returns the new row's id.

    **Idempotent on (game_id, bet_type, pick) while pending.** When
    the same opportunity already has a pending row in the tracker —
    e.g. user clicked Lock then navigated away and came back —
    record_live_pick returns the existing row's id instead of inserting
    a duplicate. Once the existing row settles (W/L/P), a fresh Lock
    on the same direction would create a new row, which is the
    intended behaviour for re-engaging after the period closes.

    Required pick fields::

        sport, game_id, matchup, bet_type, pick, odds, model_prob,
        edge_pct, snapshot {period, clock, home_score, away_score,
                            remaining_s}
    """
    sport = (sport or "").lower()
    if sport not in ("nba", "nhl", "wnba", "ncaam", "afl"):
        raise ValueError(
            f"live tracker only supports NBA/NHL/WNBA/NCAAM/AFL; "
            f"got {sport!r}"
        )

    ensure_table(sport)
    conn = get_conn(sport)
    tbl = table_name(sport)

    snap = pick.get("snapshot") or {}
    bet_type = str(pick.get("bet_type") or "")
    pick_text = str(pick.get("pick") or "")
    game_id = str(pick.get("game_id") or "")
    scope = _market_scope_from_bet_type(bet_type)

    # Stamp conviction at lock time so post-settle analytics don't
    # have to recompute it. Uses the same formula as POTD selection
    # and the live "best bet" star marker.
    from engine.live._picks import conviction_score as _conviction
    conv = _conviction(pick)

    # Dedup gate — refuse to double-record the same pending opportunity.
    # Keyed on (game_id, bet_type, pick) so different lines on the
    # same direction (Over 226.5 vs Over 227.5) still compete properly,
    # but identical re-locks (user clicks Lock, navigates away, comes
    # back, Lock looks fresh because the panel's local state reset)
    # collapse to one row.
    existing = conn.execute(
        f"SELECT id FROM {tbl} "
        f"WHERE game_id = ? AND bet_type = ? AND pick = ? "
        f"  AND result IS NULL "
        f"ORDER BY id DESC LIMIT 1",
        (game_id, bet_type, pick_text),
    ).fetchone()
    if existing:
        existing_id = int(existing["id"])
        logger.info(
            "live_tracker: dedup %s %s '%s' — already pending as id=%s",
            sport, bet_type, pick_text, existing_id,
        )
        return existing_id

    now_utc = datetime.now(timezone.utc).isoformat()
    today_local = et_today_str()

    # Per-layer probabilities for triangulation logging. Optional —
    # caller passes them when the pick was generated by an intermission
    # ensemble; continuous-live picks leave them NULL.
    layers = pick.get("layer_probs") or {}
    p_analytical = _float_or_none(layers.get("analytical"))
    p_gbm = _float_or_none(layers.get("gbm"))
    p_state_mc = _float_or_none(layers.get("state_mc"))

    # Compute stake_units for the live pick (Quarter-Kelly via the
    # same helper the prematch picks use — keeps sizing consistent
    # across live + prematch surfaces).
    stake_units = None
    try:
        from .._pick_helpers import stake_units_for
        stake_units = stake_units_for(
            float(pick.get("model_prob") or 0.0),
            float(pick.get("edge_pct") or 0.0),
            odds=int(pick.get("odds") or 0),
        )
    except Exception:
        pass

    cur = conn.execute(
        f"""
        INSERT INTO {tbl} (
            game_id, date, matchup, bet_type, pick,
            model_prob, edge, odds, stake_units, result, profit,
            created_at, settled_at, closing_odds,
            pick_at_period, pick_at_clock, pick_at_clock_secs,
            pick_at_home_score, pick_at_away_score, pick_at_remaining_s,
            market_scope, conviction_score,
            model_prob_analytical, model_prob_gbm, model_prob_state_mc
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, NULL, ?, NULL, NULL,
                  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            str(pick.get("game_id") or ""),
            today_local,
            str(pick.get("matchup") or ""),
            bet_type,
            str(pick.get("pick") or ""),
            float(pick.get("model_prob") or 0.0),
            float(pick.get("edge_pct") or 0.0),
            int(pick.get("odds") or 0),
            stake_units,
            now_utc,
            int(snap.get("period") or 0) or None,
            str(snap.get("clock") or "") or None,
            _int_or_none(snap.get("clock_secs")),
            _int_or_none(snap.get("home_score")),
            _int_or_none(snap.get("away_score")),
            _int_or_none(snap.get("remaining_s")),
            scope,
            round(float(conv), 4) if conv else None,
            p_analytical, p_gbm, p_state_mc,
        ),
    )
    conn.commit()
    new_id = cur.lastrowid
    logger.info(
        "live_tracker: recorded %s pick id=%s scope=%s %s '%s' @ %+d "
        "(model %.3f edge %+.1f%%) at %s/%s",
        sport, new_id, scope, bet_type, pick.get("pick"),
        int(pick.get("odds") or 0), float(pick.get("model_prob") or 0),
        float(pick.get("edge_pct") or 0),
        snap.get("clock"), snap.get("period"),
    )
    return int(new_id)


def _int_or_none(v):
    if v is None:
        return None
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def _float_or_none(v):
    if v is None:
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None
